version: "3.8"
services:
  tracing-server:
    image: openzipkin/zipkin
    container_name: tracing-server
    environment:
      - JAVA_OPTS=-XX:+UnlockExperimentalVMOptions -Djava.security.egd=file:/dev/./urandom
    ports:
      - 9411:9411
    networks:
      - spring-cloud-kubernetes-network

  auth-server:
    build:
      context: ./docker/keycloak
    image: zhoozhoo/spring-cloud-auth-server
    container_name: auth-server
    ports:
      - 8180:8080
    networks:
      - spring-cloud-kubernetes-network

  guest-service:
    image: zhoozhoo/spring-cloud-guest-service
    container_name: guest-service
    depends_on:
      - auth-server
    entrypoint:
      [
        "./dockerize",
        "-wait=tcp://host.docker.internal:8180",
        "-timeout=120s",
        "--",
        "java",
        "org.springframework.boot.loader.JarLauncher",
      ]
    ports:
      - 8800:8800
    networks:
      - spring-cloud-kubernetes-network

  reservation-service:
    image: zhoozhoo/spring-cloud-reservation-service
    container_name: reservation-service
    depends_on:
      - auth-server
    entrypoint:
      [
        "./dockerize",
        "-wait=tcp://host.docker.internal:8180",
        "-timeout=120s",
        "--",
        "java",
        "org.springframework.boot.loader.JarLauncher",
      ]
    ports:
      - 8801:8801
    networks:
      - spring-cloud-kubernetes-network

  room-service:
    image: zhoozhoo/spring-cloud-room-service
    container_name: room-service
    depends_on:
      - auth-server
    entrypoint:
      [
        "./dockerize",
        "-wait=tcp://host.docker.internal:8180",
        "-timeout=120s",
        "--",
        "java",
        "org.springframework.boot.loader.JarLauncher",
      ]
    ports:
      - 8802:8802
    networks:
      - spring-cloud-kubernetes-network

  room-reservation-service:
    image: zhoozhoo/spring-cloud-room-reservation-service
    container_name: room-reservation-service
    depends_on:
      - auth-server
      - room-service
      - guest-service
      - reservation-service
    entrypoint:
      [
        "./dockerize",
        "-wait=tcp://host.docker.internal:8180",
        "-timeout=120s",
        "--",
        "java",
        "org.springframework.boot.loader.JarLauncher",
      ]
    ports:
      - 8803:8803
    networks:
      - spring-cloud-kubernetes-network

  api-gateway:
    image: zhoozhoo/spring-cloud-api-gateway
    container_name: api-gateway
    depends_on:
      - auth-server
    entrypoint:
      [
        "./dockerize",
        "-wait=tcp://host.docker.internal:8180",
        "-timeout=120s",
        "--",
        "java",
        "org.springframework.boot.loader.JarLauncher",
      ]
    ports:
      - 8080:8080
    networks:
      - spring-cloud-kubernetes-network

  admin-server:
    image: zhoozhoo/spring-cloud-admin-server
    container_name: admin-server
    ports:
      - 9090:9090
    networks:
      - spring-cloud-kubernetes-network

networks:
    spring-cloud-kubernetes-network:
        driver: bridge
