apiVersion: v1
kind: Service
metadata:
  name: tracing-server
  labels:
    app: tracing-server
    group: ca.zhoozhoo.spring.cloud.kubernetes
spec:
  ports:
  - name: http
    port: &target 9411
    protocol: TCP
    targetPort: *target
  selector:
    app: tracing-server
    group: ca.zhoozhoo.spring.cloud.kubernetes
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracing-server
  labels:
    app: tracing-server
    group: ca.zhoozhoo.spring.cloud.kubernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tracing-server
      group: ca.zhoozhoo.spring.cloud.kubernetes
  template:
    metadata:
      labels:
        app: tracing-server
        group: ca.zhoozhoo.spring.cloud.kubernetes
    spec:
      containers:
      - name: tracing-server
        image: openzipkin/zipkin
        ports:
        - name: http
          containerPort: 9411
