apiVersion: v1
kind: Service
metadata:
  name: reservation-service
  labels:
    app: reservation-service
    group: ca.zhoozhoo.spring.cloud.kubernetes
spec:
  ports:
  - name: http
    port: &target 8080
    protocol: TCP
    targetPort: *target
  selector:
    app: reservation-service
    group: ca.zhoozhoo.spring.cloud.kubernetes
  type: NodePort
