apiVersion: v1
kind: Service
metadata:
  name: reservation-service
  labels:
    app: reservation-service
    group: ca.zhoozhoo.spring.cloud.kubernetes
spec:
  ports:
  - name: http
    port: &target 8080
    protocol: TCP
    targetPort: *target
  selector:
    app: reservation-service
    group: ca.zhoozhoo.spring.cloud.kubernetes
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation-service
  labels:
    app: reservation-service
    group: ca.zhoozhoo.spring.cloud.kubernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservation-service
      group: ca.zhoozhoo.spring.cloud.kubernetes
  template:
    metadata:
      labels:
        app: reservation-service
        group: ca.zhoozhoo.spring.cloud.kubernetes
    spec:
      containers:
      - name: reservation-service
        image: zhoozhoo/spring-cloud-kubernetes-reservation-service:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health/liveness
            port: &target 8080
            scheme: HTTP
          initialDelaySeconds: 180
          successThreshold: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health/readiness
            port: *target
            scheme: HTTP
          initialDelaySeconds: 10
          successThreshold: 1
        ports:
        - name: http
          containerPort: *target
