apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-gateway
    group: ca.zhoozhoo.spring.cloud.kubernetes
  name: api-gateway
spec:
  ports:
    - name: http
      port: &target 8080
      protocol: TCP
      targetPort: *target
  selector:
    app: api-gateway
    group: ca.zhoozhoo.spring.cloud.kubernetes
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: api-gateway
    group: ca.zhoozhoo.spring.cloud.kubernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
      group: ca.zhoozhoo.spring.cloud.kubernetes
  template:
    metadata:
      labels:
        app: api-gateway
        group: ca.zhoozhoo.spring.cloud.kubernetes
    spec:
      containers:
      - name: api-gateway
        image: zhoozhoo/spring-cloud-kubernetes-api-gateway:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health/livenessProbe
            port: &target 8080
            scheme: HTTP
          initialDelaySeconds: 180
          successThreshold: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health/readiness
            port: *target
            scheme: HTTP
          initialDelaySeconds: 10
          successThreshold: 1
        ports:
          - name: http
            containerPort: *target
