apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-gateway
    group: ca.zhoozhoo.spring.cloud.kubernetes
  name: api-gateway
spec:
  ports:
    - name: http
      port: &target 8080
      protocol: TCP
      targetPort: *target
  selector:
    app: api-gateway
    group: ca.zhoozhoo.spring.cloud.kubernetes
  type: LoadBalancer
