apiVersion: v1
kind: Service
metadata:
  name: tracing-server
  labels:
    app: tracing-server
spec:
  ports:
  - name: http
    port: &target 9411
    protocol: TCP
    targetPort: *target
  selector:
    app: tracing-server
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracing-server
  labels:
    app: tracing-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tracing-server
  template:
    metadata:
      labels:
        app: tracing-server
    spec:
      containers:
      - name: tracing-server
        imagePullPolicy: IfNotPresent
        image: openzipkin/zipkin
        ports:
        - name: http
          containerPort: 9411
