kind: ConfigMap
apiVersion: v1
metadata:
  name: admin-server
data:
  application.yml: |-
    server:
      port: 9090
    spring:
      cloud:
        kubernetes:
          discovery:
            service-labels:
              group: ca.zhoozhoo.spring.cloud.kubernetes
    management:
      endpoint:
        restart:
          enabled: true
        health:
          enabled: true
        info:
          enabled: true
