apiVersion: v1
kind: Service
metadata:
  labels:
    app: admin-server
    group: ca.zhoozhoo.spring.cloud.kubernetes
  name: admin-server
spec:
  ports:
  - name: http
    port: 9090
    protocol: TCP
    targetPort: 8080
  selector:
    app: admin-server
    group: ca.zhoozhoo.spring.cloud.kubernetes
  type: LoadBalancer
