apiVersion: v1
kind: Service
metadata:
  labels:
    app: admin-server
    group: ca.zhoozhoo.spring.cloud.kubernetes
  name: admin-server
spec:
  ports:
  - name: http
    port: 9090
    protocol: TCP
    targetPort: 8080
  selector:
    app: admin-server
    group: ca.zhoozhoo.spring.cloud.kubernetes
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-server
  labels:
    app: admin-server
    group: ca.zhoozhoo.spring.cloud.kubernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-server
      group: ca.zhoozhoo.spring.cloud.kubernetes
  template:
    metadata:
      labels:
        app: admin-server
        group: ca.zhoozhoo.spring.cloud.kubernetes
    spec:
      containers:
      - name: admin-server
        image: zhoozhoo/spring-cloud-kubernetes-admin-server:latest
        imagePullPolicy: IfNotPresent
        startupProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 3
          timeoutSeconds: 1
          failureThreshold: 20
          successThreshold: 1
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port:  8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 1
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        ports:
        - name: http
          containerPort: 8080
