kind: ConfigMap
apiVersion: v1
metadata:
  name: admin-server
data:
  application.yml: |-
    server:
      port: 8080
    spring:
      cloud:
        kubernetes:
          discovery:
            service-labels:
              group: ca.zhoozhoo.spring.cloud.kubernetes
    management:
      endpoint:
        health:
          enabled: true
          group:
            liveness:
              include: livenessStateProbeIndicator
            readiness:
              include: readinessStateProbeIndicator
        info:
          enabled: true
