kind: ConfigMap
apiVersion: v1
metadata:
  name: guest-service
data:
  application.yml: |-
    server:
      port: 8800
    spring:
      cloud:
        kubernetes:
          discovery:
            service-labels:
              group: ca.zhoozhoo.spring.cloud.kubernetes
      zipkin:
        baseUrl: http://tracing-server:9411
      security:
        oauth2:
          resourceserver:
            jwt:
              issuer-uri: http://auth-server:8180/auth/realms/spring-cloud-gateway-realm
    management:
      endpoint:
        restart:
          enabled: true
        health:
          enabled: true
        info:
          enabled: true
