apiVersion: v1
kind: Service
metadata:
  labels:
    app: guest-service
  name: guest-service
spec:
  ports:
  - name: http
    port: &target 8800
    protocol: TCP
    targetPort: *target
  selector:
    app: guest-service
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guest-service
  labels:
    app: guest-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guest-service
  template:
    metadata:
      labels:
        app: guest-service
    spec:
      containers:
      - name: guest-service
        image: zhoozhoo/spring-cloud-kubernetes-guest-service:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: 8800
            scheme: HTTP
          initialDelaySeconds: 180
          successThreshold: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: 8800
            scheme: HTTP
          initialDelaySeconds: 10
          successThreshold: 1
        ports:
        - name: http
          containerPort: 8800
