kind: ConfigMap
apiVersion: v1
metadata:
  name: guest-service
data:
  application.yml: |-
    server:
      port: 8080
    spring:
      cloud:
        kubernetes:
          discovery:
            service-labels:
              group: ca.zhoozhoo.spring.cloud.kubernetes
      zipkin:
        baseUrl: http://host.docker.internal:9411
      security:
        oauth2:
          resourceserver:
            jwt:
              issuer-uri: http://host.docker.internal:8180/auth/realms/spring-cloud-gateway-realm
    management:
      endpoint:
        health:
          enabled: true
          group:
        info:
          enabled: true
